version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    container_name: zero_agency_server
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - .env:/.env
      - ./db/migrations:/db/migrations
    image: server/server:multistage
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      ADDRESS: 0.0.0.0:8080
      DB_DSN: postgres://postgres:postgres@db:5432/zero_agency_db?sslmode=disable
      DB_MAX_IDLE_CONN: 4
      DB_MAX_OPEN_CONN: 4

volumes:
  db:
    driver: local
